"use client";
import { useState } from "react";
import { VerificationReport } from "./report";
import type { Report } from "@/lib/verify/types";
type Q = { id: string; question_ar: string; answer_ar: string; page: string };
export function DialogueTrainer({ questions, audiences }: { questions: Q[]; audiences: { id: string; name_ar: string; language: string }[] }) {
  const [id, setId] = useState(questions[0]?.id ?? ""), [audience, setAudience] = useState(audiences[0]?.id ?? ""), [tone, setTone] = useState("هادئ"), [answer, setAnswer] = useState(""), [result, setResult] = useState<{ question: Q; verification: Report; feedback: string } | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function check() { setBusy(true); setError(""); try { const response = await fetch("/api/dialogue", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId: id, answer }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setResult(body); } catch (e) { setError(e instanceof Error ? e.message : "تعذرت المعالجة."); } finally { setBusy(false); } }
  return <><section className="work-panel"><p className="notice">اختر جمهورك بنفسك؛ ملفات الجمهور تحتاج مراجعة لغوية متخصصة قبل استخدامها للتخصيص الآلي. التدريب يعرض جواب المصدر ويفحص الاقتباسات في إجابتك. لم يُفعّل تقييم مولّد من النموذج.</p><label htmlFor="audience">الجمهور</label><select id="audience" value={audience} onChange={e => setAudience(e.target.value)}>{audiences.map(a => <option value={a.id} key={a.id}>{a.name_ar} ({a.language})</option>)}</select><label htmlFor="tone">النبرة</label><select id="tone" value={tone} onChange={e => setTone(e.target.value)}><option>هادئ</option><option>موجز</option><option>تعليمي</option></select><label htmlFor="dialogue-question">السؤال</label><select id="dialogue-question" value={id} onChange={e => { setId(e.target.value); setResult(null); }}>{questions.map(q => <option key={q.id} value={q.id}>{q.question_ar}</option>)}</select><label htmlFor="dialogue-answer">كيف ستجيب؟</label><textarea id="dialogue-answer" rows={6} maxLength={3000} value={answer} onChange={e => setAnswer(e.target.value)} /><button className="button button-primary" disabled={busy || !answer.trim()} onClick={() => void check()}>{busy ? "جارٍ التحقّق…" : "اعرض المقارنة والتقرير"}</button></section><p role="alert">{error}</p>{result && <section className="result-card"><h2>جواب المصدر · بيّنات ص {result.question.page}</h2><blockquote>{result.question.answer_ar}</blockquote><p>{result.feedback}</p><VerificationReport report={result.verification} /></section>}</>;
}
