"use client";
import { useState } from "react";
import { VerificationReport } from "./report";
import type { Report } from "@/lib/verify/types";
type Q = { id: string; question_ar: string; answer_ar: string; page: string };
export function DialogueTrainer({ questions, audiences }: { questions: Q[]; audiences: { id: string; name_ar: string; language: string }[] }) {
  const [id, setId] = useState(questions[0]?.id ?? ""), [audience, setAudience] = useState(audiences[0]?.id ?? ""), [tone, setTone] = useState("هادئ"), [answer, setAnswer] = useState(""), [allowGemini, setAllowGemini] = useState(false), [result, setResult] = useState<{ question: Q; verification: Report; feedback: string; generated: null | { clarity: number; courtesy: number; sourceCare: number; tip: string; label: string } } | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function check() { setBusy(true); setError(""); try { const response = await fetch("/api/dialogue", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId: id, answer, allowGemini }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setResult(body); } catch (e) { setError(e instanceof Error ? e.message : "تعذرت المعالجة."); } finally { setBusy(false); } }
  return <><section className="work-panel"><p className="notice">اختر جمهورك بنفسك. أخفينا ملفَّي الجمهور المختلف فيهما بين الاسم واللغة إلى حين تصحيحهما في المصدر؛ الملفان الظاهران أيضًا يحتاجان مراجعة لغوية قبل تخصيص أي صياغة. التدريب يعرض جواب المصدر ويفحص الاقتباسات في إجابتك.</p><label htmlFor="audience">الجمهور</label><select id="audience" value={audience} onChange={e => setAudience(e.target.value)}>{audiences.map(a => <option value={a.id} key={a.id}>{a.name_ar} ({a.language})</option>)}</select><label htmlFor="tone">النبرة</label><select id="tone" value={tone} onChange={e => setTone(e.target.value)}><option>هادئ</option><option>موجز</option><option>تعليمي</option></select><label htmlFor="dialogue-question">السؤال</label><select id="dialogue-question" value={id} onChange={e => { setId(e.target.value); setResult(null); }}>{questions.map(q => <option key={q.id} value={q.id}>{q.question_ar}</option>)}</select><label htmlFor="dialogue-answer">كيف ستجيب؟</label><textarea id="dialogue-answer" rows={6} maxLength={3000} value={answer} onChange={e => setAnswer(e.target.value)} /><label className="consent-row" htmlFor="gemini-consent"><input id="gemini-consent" type="checkbox" checked={allowGemini} onChange={e => setAllowGemini(e.target.checked)} /> أوافق على إرسال إجابتي وجواب بيّنات إلى Google Gemini لتقييم الأسلوب إذا كانت الخدمة مفعّلة.</label><button className="button button-primary" disabled={busy || !answer.trim()} onClick={() => void check()}>{busy ? "جارٍ التحقّق…" : "اعرض المقارنة والتقرير"}</button></section><p role="alert">{error}</p>{result && <section className="result-card"><h2>جواب المصدر · بيّنات ص {result.question.page}</h2><blockquote>{result.question.answer_ar}</blockquote><p>{result.feedback}</p>{result.generated && <div className="notice"><strong>مولّد · تقييم أسلوب لا حكم شرعي</strong><p>الوضوح {result.generated.clarity}/5 · اللطف {result.generated.courtesy}/5 · العناية بالمصدر {result.generated.sourceCare}/5</p><p>{result.generated.tip}</p></div>}<VerificationReport report={result.verification} /></section>}</>;
}
